name: Venery
options:
  bundleIdPrefix: com.jeremyjacob
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentRegion: en
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_CFBundleDisplayName: Venery
targets:
  Venery:
    type: application
    platform: iOS
    dependencies:
      - target: VeneryWidget
        embed: true
    sources:
      - path: VeneryApp
        excludes:
          - Resources/Icons/animal-icon-sheet-source.png
    resources:
      - path: VeneryApp/Resources/list-of-animal-venery.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeremyjacob.Venery
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.education
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
  VeneryWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: VeneryWidget
      - path: VeneryApp/Models
      - path: VeneryApp/Views/AnimalIcon.swift
    resources:
      - path: VeneryWidget/Resources/list-of-animal-venery.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeremyjacob.Venery.widget
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: VeneryWidget/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  Venery:
    build:
      targets:
        Venery: all
    run:
      config: Debug
    archive:
      config: Release
